services:
  mongodb_container:
    image: mongo:latest
    container_name: telegram_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/db:/data/db

volumes:
  data: